[versions]
kotlin = "2.0.10"
ktlint = "1.2.1"

[libraries]
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.1"

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.24.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
