[versions]
kotlin = "2.2.0"
ktlint = "1.3.1"

[libraries]
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1-0.6.x-compat"

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.24.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
