[versions]
kotlin = "1.9.10"
ktlint = "0.50.0"

[libraries]
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.1"

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.23.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
